// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"hegelscheduler/api"
	"hegelscheduler/internal/app"
	"hegelscheduler/internal/config"
	"hegelscheduler/internal/core"
	"hegelscheduler/internal/data"
	"hegelscheduler/internal/server"
)

// Injectors from wire.go:

func InitializeEvent() *app.App {
	bootStrap := config.NewBootStrap()
	db := data.NewDB(bootStrap)
	jobRepo := data.NewJobRepo(db)
	jobAdminService := core.NewJobAdminService(jobRepo, bootStrap)
	jobAdminApi := api.NewJobAdminApi(jobAdminService)
	router := server.NewRouter(jobAdminApi)
	httpServer := server.NewServer(router)
	appApp := app.NewApp(httpServer)
	return appApp
}
