// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"hegelscheduler/api"
	"hegelscheduler/internal/app"
	"hegelscheduler/internal/config"
	"hegelscheduler/internal/core"
	"hegelscheduler/internal/data"
	"hegelscheduler/internal/server"
)

// Injectors from wire.go:

func InitializeEvent() *app.App {
	configConfig := config.NewConfig()
	db := data.NewDB(configConfig)
	jobRepo := data.NewJobRepo(db)
	jobService := core.NewJobService(jobRepo)
	jobApi := api.NewJobApi(jobService)
	router := server.NewRouter(jobApi)
	httpServer := server.NewServer(router)
	appApp := app.NewApp(httpServer)
	return appApp
}
